### PR TITLE
Feature/warpx fix

### PR DESCRIPTION
**Pull request by shuds13**
Minor fixes for 0.7.1 testing

### CODE REVIEW

**Comment by jlnav** [comment]
Thank you for the fixes. From what I can tell, ``all_machine_specs.py`` appears to be almost obsolete, since in the ``sim_f`` it's usage is already completely commented out and in the calling script the only value parsed from it is the path to the warpx application. We could go all the way and move ``'sim_app'`` to the configuration files and template it in the calling script. Thoughts?

**Review by jlnav — APPROVED** [review]

**Comment by shuds13** [comment]
Yes, I had not tested these changes on other platforms, but I can see that other platforms will have to be modified to use the same sim_f. So I think you are right. The sim_app at present is common for warpx tests on a given platform. I suppose its possible there could be more than one. 

E.g. Bebop could have tests on broadwell and knl nodes (though the broadwell binary should work on knl nodes - but not the other way round as the knl one will be built with avx512 extensions). 

So you can decide where is the best place to specify. I'm fine if its at the platform level for now (e.g. warpx_app)

**Comment by jlnav** [comment]
Currently, all platforms use the same calling script template, and the same ``sim_f``. Since (right now) each ``platform.json`` only includes platform-specific parameters for the submission script, ``sim_app`` will have to be duplicated into each individual test configuration for a platform. Understandably, I want to change this.

I'll also investigate if I can set it up so identical parameters in per-test configurations can supercede ``platform.json``.

**Comment by shuds13** [comment]
Warning... brainstorming to follow.

I guess there is different options here, but possible could be something like a common.json in say platforms/summit/warpx
which perhaps could be overidden by individual tests if the same field is in those. Alternatively could be in platform.json as warpx_exe or something. Perhaps the latter is better as it does not add a new thing.

I think we should allow for possibility to have more the one warpx binary on a platform. Is it possible to have something that contains binary paths in the platform.json eg. 

warpx_path =  /my/path
warpx_gpu = warpx_path/warpx_gpu.x
warpx_omp = warpx_path/warpx_omp.x

and then have the tests pick from these in the json for that test (a nested de-reference). This way, also the path is in one place. Something that someone running the tests might easily want to change.

**Pull request merged**
