### PR TITLE
Feature/pre template instructions

### PR DESCRIPTION
**Pull request by jlnav**
Preliminary steps and approach for pre-templating reminders and instructions. This helps address the common issue where the templater is used, the user realizes that they forgot to adjust some parameter in a .json configuration file, then they have to re-run the templater again after deleting previous output.

Future work includes detecting if previous output directories already exist and copying over differences instead of overwriting, adding additional notes/instructions, and finding a better solution for a tests-platforms instructions data structure, especially one that doesn't depend on test/platform hardcoded values.

Example output:

```
$ ./templater --summit --warpx

 ********** libEnsemble Scaling Tests Templater **********

Selected Platforms: Summit
Selected Tests: Warpx 

NOTICE:
Many of the templater's produced tests may require additional
Python, module, or application builds and adjustments before they will
function. The following adjustments can be made on a test-by-test basis
after templating, but we recommend performing them ahead of time:

Warpx on Summit 
 --------------- 

- Make sure WarpX is built, and the path in ./platforms/all/warpx/stage/all_machine_specs.py matches.
- Make sure your Conda environment matches in ./platforms/summit/platform.json
- Optionally make test-specific adjustments to the .json files in ./platforms/summit/warpx

(c)ontinue with templating, or any other key to exit: e
Exiting
```

### CODE REVIEW

**Comment by jlnav** [comment]
TODO: Look to Platform guides for additional platform reminders

**Comment by shuds13** [comment]
I guess the run_all.sh for warpx may need to be under platform (like the forces one), as it wont always use bsub. Unless you template it to find the launcher from a platform.json. Which might be a better way!

Are we aiming to remove all_machine_specs.py? I think this will mean  placing the warpx_exe into platform.json, and making sure json files for all tests have the relevant lines (as they do now in the summit warpx tests).

**Comment by jlnav** [comment]
> I guess the run_all.sh for warpx may need to be under platform (like the forces one), as it wont always use bsub. Unless you template it to find the launcher from a platform.json. Which might be a better way!

Good point. For now, I'll probably start by platform-specific versions of each run_all and distribute them accordingly. The corresponding feature idea is the templater iterates over and templates a list of files, besides explicitly calling and submission scripts.

> Are we aiming to remove all_machine_specs.py? I think this will mean placing the warpx_exe into platform.json, and making sure json files for all tests have the relevant lines (as they do now in the summit warpx tests).

I definitely would like to! Once this feature branch and another are pulled in, I'll do a larger WarpX refactoring.

**Comment by shuds13** [comment]
> The corresponding feature idea is the templater iterates over and templates a list of files, besides explicitly calling and submission scripts.

Not quite sure what you mean here? 

I'm thinking the run_all.sh would have something like.
{{ batch_launcher }} submit*.sh

and in platform.json:
batch_launcher: bsub

**Comment by jlnav** [comment]
I can do that. I was trying to say that currently, the templater only templates calling and submission scripts, but I could set it up where _any_ files placed into a relevant location get templated.

**Comment by shuds13** [comment]
Okay I understand the line now. I don't mind what solution for now, I am thinking from a minimal duplication point of view, but not from implementation point of view, so I will let you decide on that basis.

**Review by shuds13 — APPROVED** [review]
I think this looks good. I guess there is or will be an automated option to the interactive templater part for running on CI.

**Comment by jlnav** [comment]
> I think this looks good. I guess there is or will be an automated option to the interactive templater part for running on CI.

Very good point. There's already a separate ``ecpci`` branch, but it may be easier just to add an option to skip the reminder prompt.

**Pull request merged**
